spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 54190
help:
  default-license-id: "HUST"
  default-license-name: "Huazhong University of Science and Technology"
  default-assignee-name: Wang
  default-expiry-date: 2030-04-25